// All workspace items data

export const DESKS = [
  {
    id: 'desk-minimal',
    name: 'Mono Slim',
    tagline: 'Clean lines, zero distractions',
    price: 420,
    color: '#d4c5b0',
    legs: 4,
    style: 'minimal',
    svgKey: 'desk-minimal',
  },
  {
    id: 'desk-l-shape',
    name: 'Corner Pro',
    tagline: 'Maximum surface, maximum output',
    price: 680,
    color: '#b8a898',
    legs: 6,
    style: 'l-shape',
    svgKey: 'desk-lshape',
  },
  {
    id: 'desk-standing',
    name: 'Rise & Grind',
    tagline: 'Stand up for better ideas',
    price: 890,
    color: '#c8bca8',
    legs: 4,
    style: 'standing',
    svgKey: 'desk-standing',
  },
  {
    id: 'desk-vintage',
    name: 'Walnut Classic',
    tagline: 'Timeless craft for modern work',
    price: 760,
    color: '#8b6914',
    legs: 4,
    style: 'vintage',
    svgKey: 'desk-vintage',
  },
]

export const CHAIRS = [
  {
    id: 'chair-mesh',
    name: 'AirFlow Mesh',
    tagline: 'Breathe easy, work longer',
    price: 320,
    color: '#3a3a4a',
    style: 'mesh',
    svgKey: 'chair-mesh',
  },
  {
    id: 'chair-executive',
    name: 'Commander',
    tagline: 'Built for the long game',
    price: 550,
    color: '#1a1a2e',
    style: 'executive',
    svgKey: 'chair-executive',
  },
  {
    id: 'chair-ergonomic',
    name: 'BodySync',
    tagline: 'Your spine will thank you',
    price: 480,
    color: '#e8e0d5',
    style: 'ergonomic',
    svgKey: 'chair-ergonomic',
  },
  {
    id: 'chair-saddle',
    name: 'Kneeler Pro',
    tagline: 'Posture-perfect by design',
    price: 290,
    color: '#c85a3c',
    style: 'saddle',
    svgKey: 'chair-saddle',
  },
]

export const ACCESSORIES = [
  {
    id: 'acc-monitor-1',
    name: '27" Studio Display',
    category: 'Monitor',
    price: 280,
    emoji: '🖥️',
    description: 'Crystal clear 4K',
    maxQty: 3,
  },
  {
    id: 'acc-monitor-ultrawide',
    name: 'Ultrawide Curved',
    category: 'Monitor',
    price: 420,
    emoji: '📺',
    description: '34" immersive canvas',
    maxQty: 2,
  },
  {
    id: 'acc-lamp',
    name: 'Arc Lamp',
    category: 'Lighting',
    price: 85,
    emoji: '💡',
    description: 'Warm ambient glow',
    maxQty: 2,
  },
  {
    id: 'acc-plant-small',
    name: 'Desk Succulent',
    category: 'Plants',
    price: 25,
    emoji: '🌵',
    description: 'Low maintenance zen',
    maxQty: 3,
  },
  {
    id: 'acc-plant-tall',
    name: 'Monstera Deliciosa',
    category: 'Plants',
    price: 65,
    emoji: '🌿',
    description: 'Statement greenery',
    maxQty: 2,
  },
  {
    id: 'acc-keyboard',
    name: 'Mech Keyboard',
    category: 'Input',
    price: 145,
    emoji: '⌨️',
    description: 'Tactile satisfaction',
    maxQty: 1,
  },
  {
    id: 'acc-webcam',
    name: '4K Webcam',
    category: 'Camera',
    price: 120,
    emoji: '📷',
    description: 'Look good on calls',
    maxQty: 1,
  },
  {
    id: 'acc-speaker',
    name: 'Studio Monitors',
    category: 'Audio',
    price: 200,
    emoji: '🔊',
    description: 'Reference-quality sound',
    maxQty: 2,
  },
  {
    id: 'acc-dockstation',
    name: 'Thunderbolt Hub',
    category: 'Connectivity',
    price: 95,
    emoji: '🔌',
    description: 'One cable everything',
    maxQty: 1,
  },
  {
    id: 'acc-mousepad',
    name: 'XL Desk Mat',
    category: 'Surface',
    price: 45,
    emoji: '🟫',
    description: 'Full coverage luxury',
    maxQty: 1,
  },
  {
    id: 'acc-headphones',
    name: 'Over-Ear Pro',
    category: 'Audio',
    price: 250,
    emoji: '🎧',
    description: 'Noise-cancelling focus',
    maxQty: 1,
  },
  {
    id: 'acc-whiteboard',
    name: 'Glass Whiteboard',
    category: 'Productivity',
    price: 130,
    emoji: '📋',
    description: 'Think & erase freely',
    maxQty: 1,
  },
]

export const SECTIONS = [
  { id: 'desk', label: 'Desk', icon: '🗂️' },
  { id: 'chair', label: 'Chair', icon: '🪑' },
  { id: 'accessories', label: 'Accessories', icon: '✨' },
]
